# -*- coding: utf-8 -*-
"""Q7_b

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ewgsPxBlv48zb5jUL0_FactLM47P79kS
"""

import matplotlib.pyplot as plt
year = [1950, 1960, 1970, 1980, 1990, 2000, 2010]
data = [200, 350, 400, 150, 600, 50, 100]
plt.plot(year, data, color = 'red', linestyle='dashed', marker = '+')
plt.ylabel('Data')
plt.show()