# -*- coding: utf-8 -*-
"""Q7_c

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zWayVM2u7HnFq9Wll3DkTDx3baLOwyTK
"""

import matplotlib.pyplot as plt
movies = ['Shawshank \n Redemtion', 'Forrest \n Gump', 'Batman \n The Dark \n Knight', 'Interstella', 'The Secret Life \n of \n Walter Mitty']
award = [7,13,8,5,0]
plt.bar(range(len(movies)), award)
plt.title('My Five favourite Movies')
plt.ylabel('Number of Academy Awards')
plt.xticks(range(len(movies)), movies)
plt.show()